### PR TITLE
Update package.json and travis.yml

### PR DESCRIPTION
**Pull request by shinnn**
* I updated dependencies and devDependencies.
* I added `files` field to slim down the npm package.
* I updated .travis.yml.
  * use [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) on Travis CI
  * install the latest npm before testing
* I updated image format of the badges in README from PNG to SVG. SVG badges look beautiful on retina display.

    | PNG ver. | SVG ver. |
    | --- | --- |
    |[Build Status](https://travis-ci.org/soldair/node-gitconfiglocal)|[Build Status](https://travis-ci.org/soldair/node-gitconfiglocal)|

### CODE REVIEW

**Comment by soldair** [comment]
thanks

**Comment by shinnn** [comment]
@soldair No problem! I'd be glad if you release a new version :)

**Comment by soldair** [comment]
^ install prefix in package.json is broken in node 8 we have to either remove or fix the package.json to use ~

**Comment by shinnn** [comment]
@soldair No, the cause is my typo. I created a new PR to fix it. #3

**Pull request merged**
