### PR TITLE
add example for options.gitDir in README

### PR DESCRIPTION
**Pull request by royling**
should be part of #5

### CODE REVIEW

**Comment by royling** [comment]
also suggest to create tags for version bump, what do u think?

**Comment by soldair** [comment]
forgot to push tags. thanks.

**Comment by soldair** [comment]
I kinda prefer to leave `.git` because $GIT_DIR is fairly rare. i should probably get some sleep and ponder.
thanks for the help!

**Comment by soldair** [comment]
thanks again!

**Comment by soldair** [comment]
2.0.1

**Comment by soldair** [comment]
hey i added you as a collaborator 
this is an open opensource project so folks you contribute meaningful changes should be added =)

https://github.com/soldair/node-gitconfiglocal/blob/master/CONTRIBUTING.md

welcome!

**Comment by royling** [comment]
thanks!

**Pull request merged**
